### PR TITLE
Handle failing promises in the example

### LINKED ISSUE #5: example is not handling failing promises
related to #2

### PR DESCRIPTION
**Pull request by phra**
fixes #5 

**NOTE**: this is not fixing the `Invalid URL` error, i.e.

```
╭─phra at kali in /home/phra/git/h2url (master ✚1…2)
╰─λ node example.js                                                                                                                                             0 < 00:04:13
(node:13761) ExperimentalWarning: The http2 module is an experimental API.
{ TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at Object.request (/home/phra/git/h2url/index.js:13:15)
    at streaming (/home/phra/git/h2url/example.js:18:37)
    at Object.<anonymous> (/home/phra/git/h2url/example.js:32:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12) input: 'undefined' }
```

### CODE REVIEW

**Comment by mcollina** [comment]
I think the correct approach for this is to use https://github.com/mcollina/h2url/blob/master/h2url.js#L3. It fixes the problem at the root by crashing on unhandled rejection.

Can you update your PR?

**Comment by phra** [comment]
since it's only supporting nodejs and not browsers i will do it. :+1: 

ps: i use the `await-to` pattern as universal pattern for my frontend and backend code because:
1. it's isomorphic
1. it's enforcing an explicit _catch or escalate_ error handling that imho really improve the quality and the legibility of the code (ok, maybe not the performance :sweat_smile: )
1. let you manage the failure case without increase the nesting
1. give complete freedom to the developer on how to react to errors while forcing him/her to register a catch handler

just my 2 cents :dollar:

**Comment by mcollina** [comment]
Thanks!

**Review by phra — COMMENTED** [review]
done.

note that in `examples/example.js` i do a GET request to google, not a POST to localhost as in the `README.md`

**Comment by mcollina** [comment]
Can you split the two examples? One doing a GET with concat, and another one doing a POST to the local server?

**Comment by phra** [comment]
sure!

**Comment by phra** [comment]
done! you can launch it with `npm run example:localhost`.

EDIT: i'm removing the stream from the google example.

**Comment by phra** [comment]
ok, now the example with google works without errors. :smile:

**Review by mcollina — APPROVED** [review]

**Comment by mcollina** [comment]
Thanks!!!!

**Pull request merged**
